"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const Seeder_1 = __importDefault(global[Symbol.for('ioc.use')]("Adonis/Lucid/Seeder"));
const Groupxpermission_1 = __importDefault(global[Symbol.for('ioc.use')]("App/Models/Groupxpermission"));
class default_1 extends Seeder_1.default {
    async run() {
        await Groupxpermission_1.default.createMany([
            { usergroup_id: 1, permissiongroup_id: 1 },
            { usergroup_id: 1, permissiongroup_id: 2 },
            { usergroup_id: 1, permissiongroup_id: 3 },
            { usergroup_id: 1, permissiongroup_id: 4 },
            { usergroup_id: 1, permissiongroup_id: 5 },
            { usergroup_id: 1, permissiongroup_id: 6 },
            { usergroup_id: 1, permissiongroup_id: 7 },
            { usergroup_id: 1, permissiongroup_id: 8 },
            { usergroup_id: 1, permissiongroup_id: 9 },
            { usergroup_id: 1, permissiongroup_id: 10 },
            { usergroup_id: 1, permissiongroup_id: 11 },
            { usergroup_id: 1, permissiongroup_id: 12 },
            { usergroup_id: 1, permissiongroup_id: 13 },
            { usergroup_id: 1, permissiongroup_id: 14 },
            { usergroup_id: 1, permissiongroup_id: 15 },
            { usergroup_id: 1, permissiongroup_id: 16 },
            { usergroup_id: 1, permissiongroup_id: 17 },
            { usergroup_id: 1, permissiongroup_id: 18 },
            { usergroup_id: 1, permissiongroup_id: 19 },
            { usergroup_id: 1, permissiongroup_id: 20 },
            { usergroup_id: 1, permissiongroup_id: 21 },
            { usergroup_id: 1, permissiongroup_id: 22 },
            { usergroup_id: 1, permissiongroup_id: 23 },
            { usergroup_id: 1, permissiongroup_id: 24 },
            { usergroup_id: 1, permissiongroup_id: 25 },
            { usergroup_id: 1, permissiongroup_id: 26 },
            { usergroup_id: 1, permissiongroup_id: 27 },
            { usergroup_id: 1, permissiongroup_id: 28 },
            { usergroup_id: 1, permissiongroup_id: 29 },
            { usergroup_id: 2, permissiongroup_id: 1 },
            { usergroup_id: 2, permissiongroup_id: 5 },
            { usergroup_id: 2, permissiongroup_id: 6 },
            { usergroup_id: 2, permissiongroup_id: 15 },
            { usergroup_id: 2, permissiongroup_id: 16 },
            { usergroup_id: 2, permissiongroup_id: 17 },
            { usergroup_id: 2, permissiongroup_id: 18 },
            { usergroup_id: 2, permissiongroup_id: 19 },
            { usergroup_id: 2, permissiongroup_id: 21 },
            { usergroup_id: 2, permissiongroup_id: 22 },
            { usergroup_id: 2, permissiongroup_id: 23 },
            { usergroup_id: 2, permissiongroup_id: 24 },
            { usergroup_id: 2, permissiongroup_id: 25 },
            { usergroup_id: 2, permissiongroup_id: 26 },
            { usergroup_id: 3, permissiongroup_id: 1 },
            { usergroup_id: 3, permissiongroup_id: 15 },
            { usergroup_id: 3, permissiongroup_id: 16 },
            { usergroup_id: 3, permissiongroup_id: 17 },
            { usergroup_id: 3, permissiongroup_id: 18 },
            { usergroup_id: 3, permissiongroup_id: 19 },
            { usergroup_id: 3, permissiongroup_id: 21 },
            { usergroup_id: 3, permissiongroup_id: 22 },
            { usergroup_id: 3, permissiongroup_id: 23 },
            { usergroup_id: 3, permissiongroup_id: 24 },
            { usergroup_id: 3, permissiongroup_id: 25 },
            { usergroup_id: 3, permissiongroup_id: 26 },
            { usergroup_id: 4, permissiongroup_id: 1 },
            { usergroup_id: 4, permissiongroup_id: 15 },
            { usergroup_id: 4, permissiongroup_id: 16 },
            { usergroup_id: 4, permissiongroup_id: 17 },
            { usergroup_id: 4, permissiongroup_id: 18 },
            { usergroup_id: 4, permissiongroup_id: 19 },
            { usergroup_id: 4, permissiongroup_id: 22 },
            { usergroup_id: 4, permissiongroup_id: 23 },
            { usergroup_id: 4, permissiongroup_id: 24 },
            { usergroup_id: 4, permissiongroup_id: 26 },
            { usergroup_id: 5, permissiongroup_id: 1 },
            { usergroup_id: 5, permissiongroup_id: 15 },
            { usergroup_id: 5, permissiongroup_id: 16 },
            { usergroup_id: 5, permissiongroup_id: 17 },
            { usergroup_id: 5, permissiongroup_id: 18 },
            { usergroup_id: 5, permissiongroup_id: 23 },
            { usergroup_id: 5, permissiongroup_id: 26 },
        ]);
    }
}
exports.default = default_1;
//# sourceMappingURL=Groupxpermission.js.map