name: Build and deploy api
concurrency: deploy_production
on:
  push:
    branches:
      - main
jobs:

  build:
    name: Build api typescript project and deploy it to server
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: 20

    - run: git config --global user.email "brunofa23@gmail.com"
    - run: git config --global user.name "Bruno Favato"
    - run: git status
    - run: git checkout main-production
    - run: git pull
    - run: git merge main
    - run: pwd && npm ci
    - run: node ace build --production --ignore-ts-errors
    - run: cp -fR tmp _build
    - run: cp -fR app/Services/Validations/listMessage.json _build/app/Services/Validations/listMessage.json
    - run: git add -A
    - run: npm run release --commit-all
    - run: git push --follow-tags origin main-production


