name: Build and deploy (development-test)
concurrency: deploy_development
on:
  push:
    branches:
      - development-test

jobs:
  build:
    name: Build AdonisJS and push build to branch
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar repositório completo
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2️⃣ Configurar Node
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3️⃣ Configurar Git
      - run: |
          git config --global user.email "brunofa23@gmail.com"
          git config --global user.name "Bruno Favato"

      # 4️⃣ Garantir que estamos na branch correta
      - run: |
          git checkout development-test
          git pull origin development-test

      # 5️⃣ Instalar dependências e gerar build do Adonis
      - run: |
          npm ci
          node ace build --production --ignore-ts-errors
          mkdir -p _build/app/Services/Validations
          cp -fR tmp _build || true
          cp -f app/Services/Validations/listMessage.json _build/app/Services/Validations/listMessage.json || true

      # 6️⃣ Comitar e enviar alterações para a mesma branch
      - run: |
          git add -A
          git commit -m "chore(build): update build [skip ci]" || echo "No changes to commit"
          git push origin development-test
